# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-01-19 11:40:18 -0600 by jimmydurkin:
gem "sinatra", "~> 2.0"

# Added at 2018-01-19 11:40:27 -0600 by jimmydurkin:
gem "thin", "~> 1.7"
